<?php

function retailer_progress_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $block[0]['info'] = t('PlantRight Retailer Manager/Buyer Progress block');
    $block[0]['cache'] = BLOCK_NO_CACHE;
    $block[1]['info'] = t('PlantRight Retailer Manager/Non-buyer Progress block');
    $block[1]['cache'] = BLOCK_NO_CACHE;
    $block[2]['info'] = t('PlantRight Retailer Employee/Buyer Progress block');
    $block[2]['cache'] = BLOCK_NO_CACHE;
    $block[3]['info'] = t('PlantRight Retailer Employee/Non-Buyer Progress block');
    $block[3]['cache'] = BLOCK_NO_CACHE;
    $block[4]['info'] = t('PlantRight Partner Resources');
    $block[4]['cache'] = BLOCK_NO_CACHE;
    $block[5]['info'] = t('PlantRight Retailer COMPLETE Progress block');
    $block[5]['cache'] = BLOCK_NO_CACHE;
  }

  if ($op == 'view') {
    $block['content'] = '';

    if (arg(0) == 'user' || arg(0) == 'users') {
      if (is_numeric(arg(1))) {
        $account = user_load(arg(1));
      }
      else {
        return;
      }
    }
    else {
      global $user;
      $account = $user;
    }
    
    $account_roles = array_keys($account->roles);
    
    $content['account'] = $account;

    //$account->profile_info[] = node_load(array('uid' => $account->uid, 'type' => 'retail_member'));
    $profile = node_load(array('uid' => $account->uid, 'type' => 'retail_member'));
    if (isset($profile->field_retailer[0]['nid']) && $profile->field_retailer[0]['nid']) {
      $retailer = node_load($profile->field_retailer[0]['nid']);

      $results = db_query('select * from {content_type_retail_member} rm
                         inner join node n on n.nid = rm.nid
                         inner join users u on n.uid = u.uid
                         where rm.field_retailer_nid = %d', $retailer->nid);
      $fellow_citizens = array();
      while ($result = db_fetch_object($results)) {
        array_push($fellow_citizens, user_load($result->uid));
      }
    }
    else {
      $retailer = NULL;
      $fellow_citizens = array();
    }
    
    // If progress is complete, and it's come this far, hide the progress box.
    if ($retailer->field_is_certified[0]['value'] == 1 && in_array(11, $account_roles)){
      $content['progress_complete'] = TRUE;
    }
    else {
      $content['progress_complete'] = FALSE;
    }

    switch ($delta) {
      case 0:
        //If user is not a manager/buyer, show empty block.
        if (!in_array(7, $account_roles)) {
          return $block;
        }
        break;

      case 1:
        //If user is not an manager/non-buyer, show empty.
        if (!in_array(8, $account_roles)) {
          return $block;
        }
        break;

      case 2:
        // If a user is not an employee/buyer, show empty.
        if (!in_array(9, $account_roles)) {
          return $block;
        }
        break;

      case 3:
        // If a user is not an employee/non-buyer, show empty.
        if (!in_array(10, $account_roles)) {
          return $block;
        }
        break;
      case 4:
        $content['user_roles'] = $account_roles;
        $block['content'] = $content;
        return $block;
        break;
      case 5:
        // If user has completed quiz & nursery partnered.
        if (!$content['progress_complete']) {
          return;
        }
        break;
    }  

    $content['profile_nid'] = $profile->nid;
    $content['retailer_nid'] = isset($retailer->nid) ? $retailer->nid : NULL;
    $content['liaison'] = $retailer->uid == $account->uid;

    //Has this manager registered a retailer yet?
    $content['store_registered'] = $retailer ? "complete" : "incomplete";

    //Has this manager invited their employees yet?
    $results = db_query('select * from invite where uid = %d and canceled = 0', $account->uid);
    $invites = array();
    while ($result = db_fetch_object($results)) {
      array_push($invites, $result);
    }
    $content['invites'] = $results ? $invites : NULL;

    //Have the employees which were invited followed through and registered yet?
    $accepted_invites = array();
    $ignored_invites = array();
    foreach ($invites as $invite) {
      if ($invite->joined == 0) {
        array_push($ignored_invites, $invite);
      }
      else {
        array_push($accepted_invites, $invite);
      }
    }

    $content['ignored_invites'] = $ignored_invites;
    $content['accepted_invites'] = $accepted_invites;

    //Have plant buyers reviewed the training materials?
    // There's no real way to tell this one,
    // so we'll just set it to passed when the individual has passed the quiz
    //Have all the plant buyers passed the quiz (verified role)?
    $registered_nonbuyers = array();
    $certified_nonbuyers = array();
    $slacker_nonbuyers = array();
    $registered_buyers = array();
    $certified_buyers = array();
    $slacker_buyers = array();

    foreach ($fellow_citizens as $citizen) {
      $rids = array_keys($citizen->roles);
      // If the user is a buyer
      if (in_array(7, $rids) || in_array(9, $rids)) {
        $registered_buyers[] = $citizen;
        // And if they've passed the quiz
        if (in_array(11, $rids)) {
          $certified_buyers[] = $citizen;
        }
        else {
          // Otherwise, they are a slacker
          $slacker_buyers[] = $citizen;
        }
      }
      else {
        $registered_nonbuyers[] = $citizen;
        if (in_array(11, $rids)) {
          $certified_nonbuyers[] = $citizen;
        }
        else {
          $slacker_nonbuyers[] = $citizen;
        }
      }
    }

    $total_buyers_count = isset($retailer->field_number_of_buyers[0]) ? $retailer->field_number_of_buyers[0]['value'] : 0;
    // If the number of registered buyers is larger than the total buyers
    // indicated on the form, show registered buyers so it's not confusing.
    $registered_buyers_count = count($registered_buyers);
    if ($total_buyers_count < $registered_buyers_count) {
      $total_buyers_count = $registered_buyers_count;
    }
    // Total registered staff.
    $content['registered_staff_count'] = count($fellow_citizens);
    // Array of registered nonbuyer employees.
    $content['registered_nonbuyers'] = $registered_nonbuyers;
    // Array of nonbuyers who have passed the quiz.
    $content['certified_nonbuyers'] = $certified_nonbuyers;
    // Array of nonbuyers who have not passed the quiz.
    $content['slacker_nonbuyers'] = $slacker_nonbuyers;

    // Boolean for if the account user has the role that passed the quiz.
    $content['account_quiz_status'] = in_array(11, $account_roles) ? TRUE : FALSE;
    // Number of total buyers count from the Retailer node. (Manually entered value.)
    $content['total_buyers_count'] = $total_buyers_count;
    // Array of users associated to the Retailer node who have a plant buyer role.
    $content['registered_buyers'] = $registered_buyers;
    // Array of the registered_buyers that have passed the certification quiz.
    $content['certified_buyers'] = $certified_buyers;
    // Array of registered_buyers who haven't passed the certification quiz.
    $content['slacker_buyers'] = $slacker_buyers;

    $block['content'] = $content;
  }

  return $block;
}
