<?php

/**
 * Implements hook_menu_alter().
 */
function plantright_ecomm_menu_alter(&$items) {
  // Override the access to the cart with custom access.
  $access_args = array('access plantright ecomm pages');
  $items['cart']['access arguments'] = $access_args;
  $items['cart/checkout']['access arguments'] = $access_args;
  $items['cart/checkout/review']['access arguments'] = $access_args;
  $items['cart/checkout/complete']['access arguments'] = $access_args;
  $items['cart/checkout/line_items']['access arguments'] = $access_args;
  $items['cart/checkout/payment_details/%']['access arguments'] = $access_args;
}

/**
 * Implements hook_perm().
 */
function plantright_ecomm_perm() {
  return array(
    'access plantright ecomm pages',
  );
}

function plantright_ecomm_access() {
  return user_access('access plantright ecomm pages');
}

/**
 * Implements hook_form_alter().
 */
function plantright_ecomm_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'uc_cart_checkout_form':
      drupal_add_js("$('#uc-cart-checkout-form').submit(function() {
        $('#edit-panes-billing-copy-address').attr('checked', 'checked');
        uc_cart_copy_address($('#edit-panes-billing-copy-address')[0].checked, 'delivery', 'billing');
      });", 'inline');

      // Hide the payment pane until we need to collect payments.
      $form['panes']['payment']['#attributes']['style'] = 'display: none;';
      $form['panes']['billing']['#attributes']['style'] = 'display: none;';

      // Insert user's nursery by default
      //$form['panes']['delivery']['delivery_company']['#type'] = 'select';
      $account = user_load($form['uid']['#value']);
      $nursery_name = plantright_get_user_profile_nursery($account, FALSE);
      $nurseries = plantright_get_partner_nurseries(FALSE);
      $options = array('' => t('- Select -'));
      foreach ($nurseries as $nursery) {
        $options[$nursery['node_title']] = $nursery['node_title'];
      }

      // Set the form company fields to use the plantright company fields.
      $form['panes']['delivery']['delivery_company']['#title'] = t('Nursery');
      $form['panes']['delivery']['delivery_company']['#default_value'] = $nursery_name;
      $form['panes']['delivery']['delivery_company']['#type'] = 'select';
      unset($form['panes']['delivery']['delivery_company']['#size']);
      $form['panes']['delivery']['delivery_company']['#options'] = $options;
      $form['panes']['delivery']['delivery_company']['#required'] = TRUE;
      //$form['panes']['delivery']['delivery_company']['#disabled'] = TRUE;
      $form['panes']['delivery']['delivery_zone']['#default_value'] = 12;
      
      $form['panes']['billing']['billing_company']['#title'] = t('Nursery');
      $form['panes']['billing']['billing_company']['#default_value'] = $nursery_name;
      $form['panes']['billing']['billing_company']['#type'] = 'select';
      unset($form['panes']['billing']['billing_company']['#size']);
      $form['panes']['billing']['billing_company']['#options'] = $options;
      $form['panes']['billing']['billing_company']['#required'] = TRUE;
      //$form['panes']['billing']['billing_company']['#disabled'] = TRUE;
      $form['panes']['billing']['billing_zone']['#default_value'] = 12;
      
      
      break;
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function plantright_ecomm_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['uc_cart_checkout_review']['function'])) {
    $path = drupal_get_path('module', 'plantright_ecomm' . '/plantright_ecomm.module');
    $theme_registry['uc_cart_checkout_review']['function'] = 'plantright_ecomm_uc_cart_checkout_review';
    $theme_registry['uc_cart_checkout_review']['file'] = $path;
    $theme_registry['uc_cart_checkout_review']['theme path'] = $path;
  }
}

/**
 * Override of checkeout review theme.
 * Handles removing the billing info on free order.
 */
function plantright_ecomm_uc_cart_checkout_review($panes, $form) {
  drupal_add_css(drupal_get_path('module', 'uc_cart') .'/uc_cart.css');

  $output = check_markup(variable_get('uc_checkout_review_instructions', uc_get_message('review_instructions')), variable_get('uc_checkout_review_instructions_format', FILTER_FORMAT_DEFAULT), FALSE)
           .'<table class="order-review-table">';

  foreach ($panes as $title => $data) {
    // Remove billing info if free order.
    if (($title == t('Billing information') || $title == t('Payment method')) && $panes[t('Payment method')][count($panes[t('Payment method')]) - 1]['data'] == t('Free order')) {
      continue;
    }
    $output .= '<tr class="pane-title-row">';
    $output .= '<td colspan="2">' . $title . '</td>';
    $output .= '</tr>';
    if (is_array($data)) {
      foreach ($data as $row) {
        if (is_array($row)) {
          if (isset($row['border'])) {
            $border = ' class="row-border-'. $row['border'] . '"';
          }
          else {
            $border = '';
          }
          $output .= '<tr valign="top"' . $border . '>';
          $output .= '<td class="title-col">' . $row['title'] . ':</td>';
          $output .= '<td class="data-col">' . $row['data'] . '</td>';
          $output .= '</tr>';
        }
        else {
          $output .= '<tr valign="top"><td colspan="2">' . $row . '</td></tr>';
        }
      }
    }
    else {
      $output .= '<tr valign="top"><td colspan="2">' . $data . '</td></tr>';
    }
  }

  $output .= '<tr class="review-button-row">';
  $output .= '<td colspan="2">' . $form . '</td>';
  $output .= '</tr>';

  $output .= '</table>';

  return $output;
}
