<?php
// $Id$
/**
 * @file
 * Scores the user's quiz and givers them privileges if they pass.
 */

function score_quiz_quiz_finished($quiz, $score, $rid) {
	global $user
	
	if($score >= 80) {
		db_query('INSERT INTO {users_roles} (uid, rid) VALUES (%d, %d)', $user->uid, 4);
		drupal_set_message(t('Congratulations, you passed the quiz.  You may procede to the instructions page.'));
	}
	else {
		drupal_set_message(t('You did not pass the quiz.  Please try again.'));
	}
}