<?php

function plantright_flag($action, $flag, $content_id, $account) {
	if($action == 'flag' && $flag->name == 'nursery_flag') {
		$node = node_load($content_id);
		//dpm($node->field_surveying_user);
		$member = array();
		$member['uid'] = $account->uid;
		array_push($node->field_surveying_user, $member);
		//dpm($node->field_surveying_user);
		node_save($node);
	}
	if($action == 'unflag' && $flag->name == 'nursery_flag') {
	  $node = node_load($content_id);
	  $users = $node->field_surveying_user;
	  $node->field_surveying_user = removeElementWithValue($users, "uid", $account->uid);
	  node_save($node);
	}  
}

function removeElementWithValue($array, $key, $value){
  foreach($array as $subKey => $subArray){
    if($subArray[$key] == $value){
      unset($array[$subKey]);
    }
  }
  return $array;
}



function plantright_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'login') {
    //dpm($account);
    //dpm($edit);
  }
}

function plantright_nodeapi(&$node, $op) {
  //if ($node->type == 'retail_member') {
  //  dpm($node);
  //}
}

function _plantright_role_sender(&$form, &$form_state) {
  global $user;
  $node = node_load(array('uid' => $account->uid, 'type' => 'retail_member'));
  $rids = array_keys($user->roles);
  if ($node->field_retailer[0]['nid'] == NULL) {
    if (in_array(7, $rids) || in_array(8, $rids)) {
      $form_state['redirect'] = 'node/add/business';
    }
  }
}

function _plantright_pass_reset($form, &$form_state) {
  global $user;
  $rids = array_keys($user->roles);
  if (in_array(7, $rids) || in_array(8, $rids) || 
      in_array(9, $rids) || in_array(10, $rids)) {
    drupal_set_message('Please enter your new password', 'status');
    $form_state['redirect'] = 'user/$user->rid/profile/retail_member';
  }
}

function plantright_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register') {
    $form['account']['mail']['#description'] = 'A valid e-mail address. All e-mails from the system will be sent to this address.<br />
      The e-mail address is not made public and your information will not be sold, or shared with others.';
    return $form;
  }
  if ($form_id == 'user_login' || $form_id == 'user_login_block') {
    $form['#action'] = NULL;
    $form['#submit'] = array('_plantright_role_sender');
  }
  if ($form_id == 'user_pass_reset') {
    $form['#redirect'] = 'user';
    dpm($form);
  }
}

