<?php

DEFINE('PLANTRIGHT_RETAIL_PROFILE', 'retail_member');
DEFINE('PLANTRIGHT_RETAIL_PROFILE_NURSERY', 'field_retailer');

DEFINE('PLANTRIGHT_CONTINUING_EDUCATION_PROFILE', 'continuing_education_member');
DEFINE('PLANTRIGHT_SURVEY_PROFILE', 'survey_profile');

DEFINE('PLANTRIGHT_PROFILE_FNAME', 'field_fname');
DEFINE('PLANTRIGHT_PROFILE_LNAME', 'field_lname');


/**
 * Include token support.
 */
require_once drupal_get_path('module', 'plantright') . '/plantright_token.inc';

function plantright_flag($action, $flag, $content_id, $account) {
  if ($action == 'flag' && $flag->name == 'nursery_flag') {
    $node = node_load($content_id);
    //dpm($node->field_surveying_user);
    $member = array();
    $member['uid'] = $account->uid;
    array_push($node->field_surveying_user, $member);
    //dpm($node->field_surveying_user);
    node_save($node);
  }
  if ($action == 'unflag' && $flag->name == 'nursery_flag') {
    $node = node_load($content_id);
    $users = $node->field_surveying_user;
    $node->field_surveying_user = removeElementWithValue($users, "uid", $account->uid);
    node_save($node);
  }
}

function removeElementWithValue($array, $key, $value) {
  foreach ($array as $subKey => $subArray) {
    if ($subArray[$key] == $value) {
      unset($array[$subKey]);
    }
  }
  return $array;
}

function plantright_user($op, &$edit, &$account, $category = NULL) {
  //dpm(array($op, $account));
  if ($op == 'login') {
    //dpm($account);
    //dpm($edit);
  }
}

function plantright_nodeapi(&$node, $op) {
  // When retail manager creates a Retailer, set the association
  if ($node->type == 'business' && $op == 'insert') {
    $retail_member = node_load(array('uid' => $node->uid, 'type' => 'retail_member'));
    $retail_member->field_retailer[0]['nid'] = $node->nid;
    node_save($retail_member);
  }
  //dpm($node);
}

function _plantright_login_action(&$form, &$form_state) {
  global $user;
  $rids = array_keys($user->roles);
  // if a Retailer member,
  if (in_array(7, $rids) ||
      in_array(8, $rids) ||
      in_array(9, $rids) || 
      in_array(10, $rids) ||
      in_array(15, $rids)) {
    drupal_goto("user/$user->uid");
  }
//  $node = node_load(array('uid' => $account->uid, 'type' => 'retail_member'));
//  $rids = array_keys($user->roles);
//  //If a manager and hasn't registered a store, redirect to node/add/business form
//  if ($node->field_retailer[0]['nid'] == NULL) {
//    if (in_array(7, $rids) || in_array(8, $rids)) {
//      $form_state['redirect'] = 'node/add/business';
//    }
//  }
//  //If an employee, handle that
//  if (in_array(9, $rids) || in_array(10, $rids)) {
//    // If verified, go to resources
//    if (in_array(11, $rids)) {
//      drupal_goto('partner-resources');
//    } else {
//      // If not verified, go to training
//      drupal_goto('plantright-101-training');
//    }
//  }
}

function plantright_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if ($form_id == 'user_register') {
//    $form['#tree'] = TRUE;
    $form['account']['mail']['#description'] = 'A valid e-mail address. All e-mails from the system will be sent to this address.<br />
      The e-mail address is not made public and your information will not be sold, or shared with others.';
    $form['name']['#type'] = 'hidden';
    $form['name']['#default_value'] = user_password();
    $form['#after_build'] = array('plantright_user_register_after_build');
  }
  if ($form_id == 'user_login' || $form_id == 'user_login_block') {
    $form['#action'] = NULL;
    $form['#submit'] = array('_plantright_login_action');
  }
  if ($form_id == 'user_pass_reset') {
    $form['#redirect'] = 'user';
  }
  if ($form_id == 'node_form' && $form['type'] == 'retail_member') {
    $form['contact']['#prefix'] = '<div class="contact-info">';
    $form['contact']['#suffix'] = '</div>';
  }
  if ($form_id == 'continuing_education_member_node_form' || $form_id == 'survey_profile_node_form' || $form_id == 'retail_member_node_form') {
    $form['title']['#type'] = 'hidden';
    if (isset($form['account']['name'])) {
      $form['account']['name']['#type'] = 'hidden';
    }
    $form['#after_build'] = array('plantright_user_register_after_build');

    if ($user->uid) {
      $form['#redirect'] = "user/$user->uid";
    }
    else {
      $form['#redirect'] = "user";
    }
  }
  if ($form_id == 'business_node_form') {
    $form['#redirect'] = 'invite';
    $form['buttons']['submit']['#value'] = 'Register Store';
    //$form['#']
    //dpm($form);

    $nursery_name = isset($form_state['values']['title']) ? $form_state['values']['title'] : '';

    $pledge = <<<PLEDGE
      <h3>RETAIL PARTNER AGREEMENT (for pilot program)</h3>

      <p>This agreement is entered between <span class="nursery-name">$nursery_name</span> and Sustainable Conservation, a 501c3 nonprofit that runs the PlantRight initiative. Since 2005, Sustainable Conservation has been collaborating with California’s horticultural industry to identify cost-effective, voluntary measures to stop the sale of known invasive plants and to prevent the introduction of new invasive varieties. Sustainable Conservation recognizes nursery retailers’ leadership role in increasing consumer awareness about the serious, costly problem posed by invasive plants. This joint-partnership effort aims to promote healthy local economies and ecosystems by encouraging the sale of non-invasive, climate-appropriate plants for California gardens and landscapes.</p>

      <p>As an authorized representative of <span class="nursery-name">$nursery_name</span>, our store agrees to adopt the principles of PlantRight during this pilot program (from the present date to June 2013). As part of this agreement:</p>

      <p>We recognize that:</p>
<ul>
      <li>Invasive plants are a threat to California’s natural ecosystems and economy. They crowd out existing plants and wildlife, increase fire severity, reduce agricultural yields, decrease land value, impact water supply, and degrade recreational opportunities. Over $82 million is spent managing invasive plants in our state each year, yet they continue to spread.</li>
      <li>California’s nursery industry has a key role to play in preventing the introduction and proliferation of invasive plants.</li>
      <li>Offering non-invasive plants to our customers is a key component to providing regionally appropriate plant recommendations.</li>
      <li>PlantRight conducts a survey of randomly selected nurseries each spring to document the availability of the invasive plants on its list. This is a voluntary, non-regulatory effort through which the identity of surveyed stores is protected and only aggregated data is publicly released.</li>
</ul>
      <p>We agree to:</p>
<ul>
      <li>Refrain from selling plants that PlantRight lists as being invasive in our region.</li>
      <li>Have all staff responsible for making plant buying decisions complete the PlantRight 101 training course and pass the test online. (The training and test can be completed in under 30 min.)</li>
      <li>Encourage all sales staff to complete the PlantRight 101 training course and pass the test.</li>
      <li>Make every reasonable effort to communicate our PlantRight policy to staff, customers and vendors. (Communication vehicles may include: staff training, print materials, customer service, do-not-buy lists, email, website and social media.)</li>
      <li>Appoint a PlantRight liaison as a primary point of contact.</li>
      <li>Revisit this agreement with PlantRight on an annual basis as PlantRight’s invasive plant list is annually reviewed and may change as new information becomes available.</li>
</ul>

      <p>We will receive:</p>
<ul>
      <li>Free PlantRight 101 training for our staff.</li>
      <li>Online access to PlantRight’s Partner Toolkit and educational resources (e.g. the latest PlantRight invasive plants list, editorial content, research, on-going training materials and invasive plant trivia, as well as marketing materials, signage, etc.) to help communicate our PlantRight policy to customers, staff and vendors.</li>
      <li>90-days advance notice, should any new plants be added to the PlantRight invasive plants list.</li>
      <li>A list of non-invasive plants to recommend to customers and vendors as suitable alternatives to the plants on PlantRight’s invasive list.</li>
      <li>Recognition for our commitment to, and collaboration with, PlantRight. This recognition will take the form of publicity via quarterly PlantRight press coverage and articles (online and offline).*</li>
      <li>Listing (our company name and contact information) in PlantRight’s online business directory.*</li>
</ul>
PLEDGE;
    $form['field_pledge']['#prefix'] = $pledge;
  }
  if ($form_id == 'invite_form') {
    $form['#redirect'] = 'user';
  }

  /* from changes to account_profile module */
  if (variable_get('content_profile_use_' . $form['#node']->type, FALSE)
      && content_profile_page_access($form['#node']->type, $user)) {
    $profile = $form_id;
  }
  switch ($form_id) {
    case 'user_profile_form':
      if (variable_get('account_profile_redirect', TRUE)) {
        if (isset($_REQUEST['destination'])) {
          $destination = $_REQUEST['destination'];
          unset($_REQUEST['destination']);
          drupal_goto($_GET['q'] . "/$profile", array('destination' => $destination));
        }
        else {
          drupal_goto($_GET['q'] . "/$profile");
        }
        // header("Location: " . base_path() . $_GET['q'] . "/$profile");
        exit;
      }
      break;
    case $profile:
      /* integration with account form */
      if (is_numeric(arg(1))) { // activate only on edit page (not on registration page)
        // check if we are on a user account or node edit page
        if (arg(0) == 'user') { // on account edit page
          $user = user_load(arg(1));
        }
        elseif (arg(0) == 'node') { // on content profile node edit page
          $node = node_load(arg(1));
          $user = user_load($node->uid);
        }

        module_load_include('pages.inc', 'user');

        $form['account_profile_uid'] = array(
          '#type' => 'value',
          '#value' => $user->uid,
        );
        //Remove account so in case its set, account form version is used.
        $form['account'] = NULL;
        unset($form['account']);
        $account_form = user_profile_form(array(), $user);
        unset($account_form['submit'], $account_form['delete']); // remove duplicated Save button and Delete
        $form = array_merge($form, $account_form);
        $form['#validate'][] = 'account_profile_form_validate';
        $form['#validate'][] = 'user_validate_picture';
        $form['#submit'][] = 'account_profile_form_submit';
        $form['#submit'][] = 'account_profile_user_profile_submit';

        // Reorder the form elements.
        $form['mimemail']['#weight'] = $form['contact']['#weight'] = 100;
        $form['account']['#weight'] = 90;
      }
      /* Integration with Notifications autosubscribe module  */
      if (module_exists('notifications_autosubscribe')) {
        // Call hook_form_alter from notifications_autosubscribe
        // Simulating we are on the user edit form so the
        // autosubscribe check box is included on the form
        notifications_autosubscribe_form_alter($form, $form_state, 'user_profile_form');
      }
      break;
    default:
  }
}

function plantright_user_register_after_build(&$form, &$form_state) {
  $form['field_retailer']['nid']['nid']['#options'][''] = t('Store not registered yet');
  return $form;
}

function plantright_menu_alter(&$items) {
  $items['user/reset/%/%/%'] = array(
    'title' => 'Reset password',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plantright_user_pass_reset', 2, 3, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
}

/**
 * Menu callback; process one time login link and redirects to the user page on success.
 */
function plantright_user_pass_reset(&$form_state, $uid, $timestamp, $hashed_pass, $action = NULL) {
  global $user;

  // Check if the user is already logged in. The back button is often the culprit here.
  if ($user->uid) {
    drupal_set_message(t('You have already used this one-time login link. It is not necessary to use this link to login anymore. You are already logged in.'));
    drupal_goto();
  }
  else {
    // Time out, in seconds, until login URL expires. 24 hours = 86400 seconds.
    $timeout = 86400;
    $current = time();
    // Some redundant checks for extra security ?
    if ($timestamp < $current && $account = user_load(array('uid' => $uid, 'status' => 1))) {
      // Deny one-time login to blocked accounts.
      if (drupal_is_denied('user', $account->name) || drupal_is_denied('mail', $account->mail)) {
        drupal_set_message(t('You have tried to use a one-time login for an account which has been blocked.'), 'error');
        drupal_goto();
      }

      // No time out for first time login.
      if ($account->login && $current - $timestamp > $timeout) {
        drupal_set_message(t('You have tried to use a one-time login link that has expired. Please request a new one using the form below.'));
        drupal_goto('user/password');
      }
      else if ($account->uid && $timestamp > $account->login && $timestamp < $current && $hashed_pass == user_pass_rehash($account->pass, $timestamp, $account->login)) {
        // First stage is a confirmation form, then login
        if ($action == 'login') {
          watchdog('user', 'User %name used one-time login link at time %timestamp.', array('%name' => $account->name, '%timestamp' => $timestamp));
          // Set the new user.
          $user = $account;
          // user_authenticate_finalize() also updates the login timestamp of the
          // user, which invalidates further use of the one-time login link.
          user_authenticate_finalize($form_state['values']);
          drupal_set_message(t('You have just used your one-time login link. It is no longer necessary to use this link to login.'));
          $rids = array_keys($user->roles);

          if (in_array(7, $rids) || in_array(8, $rids) || in_array(9, $rids) || in_array(10, $rids)) {
            $node = node_load(array('type' => 'retail_member', 'uid' => $user->uid));
            drupal_set_message('Please reset your password.', 'status');

            if ($node) {
              drupal_goto('node/' . $node->nid . '/edit');
            }
            else {
              drupal_goto();
            }
          }
          elseif (in_array(14, $rids)) {
            $node = node_load(array('type' => 'survey_profile', 'uid' => $user->uid));
            drupal_set_message('Please reset your password.', 'status');
            if ($node) {
              drupal_goto('node/' . $node->nid . '/edit');
            }
            else {
              drupal_goto();
            }
          }
          else {
            drupal_goto('user/' . $user->uid);
          }
        }
        else {
          $form['message'] = array('#value' => t('<p>This is a one-time login for %user_name and will expire on %expiration_date.</p><p>Click on this button to login to the site and change your password.</p>', array('%user_name' => $account->name, '%expiration_date' => format_date($timestamp + $timeout))));
          $form['help'] = array('#value' => '<p>' . t('This login can be used only once.') . '</p>');
          $form['submit'] = array('#type' => 'submit', '#value' => t('Log in'));
          $form['#action'] = url("user/reset/$uid/$timestamp/$hashed_pass/login");
          return $form;
        }
      }
      else {
        drupal_set_message(t('You have tried to use a one-time login link which has either been used or is no longer valid. Please request a new one using the form below.'));
        drupal_goto('user/password');
      }
    }
    else {
      // Deny access, no more clues.
      // Everything will be in the watchdog's URL for the administrator to check.
      drupal_access_denied();
    }
  }
}

/**
 * Implementation of hook_mail_alter().
 */
function plantright_mail_alter(&$message) {
  switch ($message['id']) {
    // For the invite, set the inviter's name to their profile name.
    // Instead of their user account name.
    case 'invite_invite':
      $inviter_user = user_load(array('mail' => $message['from']));
      if ($inviter_user_name = plantright_get_user_profile_name($inviter_user)) {
        $message['from'] = $inviter_user_name . '<' . $inviter_user->mail . '>';
        $message['headers']['From'] = $inviter_user_name . '<' . $inviter_user->mail . '>';
      }
      break;
  }
}

/**
 * Helper function. Returns user's profile name.
 */
function plantright_get_user_profile_name($account) {
  static $plantright_user_profile_name;
  if (!isset($plantright_user_profile_name)) {
    $profile = NULL;
    if ($profile = content_profile_load(PLANTRIGHT_RETAIL_PROFILE, $account->uid)) {
    }
    else if ($profile = content_profile_load(PLANTRIGHT_CONTINUING_EDUCATION_PROFILE, $account->uid)) {
    }
    else if ($profile = content_profile_load(PLANTRIGHT_SURVEY_PROFILE, $account->uid)) {
    }
      
    if ($profile) {
      // Profile exists. Replace the username with the profile name
      $fname = $profile->{PLANTRIGHT_PROFILE_FNAME};
      if ($fname) {
        $fname = $fname[0]['value'];
        $name = $fname;
      }
      $lname = $profile->{PLANTRIGHT_PROFILE_LNAME};
      if ($lname) {
        $lname = $lname[0]['value'];
        $name = $name . ($name ? ' ' : '') . $lname;
      }
    }
    $plantright_user_profile_name = $name ? $name : $account->name;
  }

  return $plantright_user_profile_name;
}

/**
 * Helper function. Returns user's profile nursery.
 */
function plantright_get_user_profile_nursery($account) {
  static $plantright_user_profile_nursery;
  if (!isset($plantright_user_profile_nursery)) {
    if ($profile = content_profile_load(PLANTRIGHT_RETAIL_PROFILE, $account->uid)) {
      if ($profile->{PLANTRIGHT_RETAIL_PROFILE_NURSERY} && isset($profile->{PLANTRIGHT_RETAIL_PROFILE_NURSERY}[0]) && $nursery_nid = $profile->{PLANTRIGHT_RETAIL_PROFILE_NURSERY}[0]['nid']) {
        $nursery = node_load($nursery_nid);
        if ($nursery) {
          $nursery_name = check_plain($nursery->title);
        }
      }
    }
    $plantright_user_profile_nursery = $nursery_name ? $nursery_name : 'our nursery';
  }
  return $plantright_user_profile_nursery;
}
