<?php

function plantright_flag($action, $flag, $content_id, $account) {
	if($action == 'flag' && $flag->name == 'nursery_flag') {
		$node = node_load($content_id);
		//dpm($node->field_surveying_user);
		$member = array();
		$member['uid'] = $account->uid;
		array_push($node->field_surveying_user, $member);
		//dpm($node->field_surveying_user);
		node_save($node);
	}
	if($action == 'unflag' && $flag->name == 'nursery_flag') {
	  $node = node_load($content_id);
	  $users = $node->field_surveying_user;
	  $node->field_surveying_user = removeElementWithValue($users, "uid", $account->uid);
	  node_save($node);
	}  
}

function removeElementWithValue($array, $key, $value){
  foreach($array as $subKey => $subArray){
    if($subArray[$key] == $value){
      unset($array[$subKey]);
    }
  }
  return $array;
}



function plantright_user($op, &$edit, &$account, $category = NULL) {
  //dpm($account);
}

function plantright_nodeapi(&$node, $op) {

}

function plantright_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register') {
    $form['account']['mail']['#description'] = 'A valid e-mail address. All e-mails from the system will be sent to this address.<br />
      The e-mail address is not made public and your information will not be sold, or shared with others.';
    return $form;
  }
}
