<?php
/**
 * @file
 * Module code for schedule email
 */
DEFINE('QUIZ_CERTIFICATE_PROFILE', 'retail_member');
DEFINE('QUIZ_CERTIFICATE_PROFILE_FNAME', 'field_fname');
DEFINE('QUIZ_CERTIFICATE_PROFILE_LNAME', 'field_lname');

/**
 * Implementation of hook_menu().
 */
function quiz_certificate_menu() {

  // Take quiz.
  $items['node/%node/certificate'] = array(
    'title' => 'My Certificate',
    'page callback' => 'quiz_certificate_my_certificate',
    'page arguments' => array(1),
    'access callback' => 'quiz_certificate_access_my_certificate',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%node/certificate/pdf'] = array(
    'title' => 'My Certificate',
    'page callback' => 'quiz_certificate_my_certificate_pdf',
    'page arguments' => array(1),
    'access callback' => 'quiz_certificate_access_my_certificate',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  $items['node/%node/results/%/certificate'] = array(
    'title' => 'Certificate',
    'page callback' => 'quiz_certificate_admin_certificate',
    'page arguments' => array(1, 3),
    'type' => MENU_CALLBACK,
    'access arguments' => array(1, 3),
    'access callback' => 'quiz_certificate_access_certificates',
  );
  $items['node/%node/results/%/certificate/pdf'] = array(
    'title' => 'Certificate',
    'page callback' => 'quiz_certificate_admin_certificate_pdf',
    'page arguments' => array(1, 3),
    'access arguments' => array(1, 3),
    'access callback' => 'quiz_certificate_access_certificates',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function quiz_certificate_perm() {
  return array(
    'view own quiz certificate', 
    'view any quiz certificate',
    'view certificates for own quiz',
  );
}

/**
 * Helper function to determine if a user has access to view their certificate
 *
 * @param object $quiz
 *  The Quiz node
 */
function quiz_certificate_access_my_certificate($quiz) {
  global $user;
  if ($quiz->type !== 'quiz') {
    return FALSE;
  }

  if(!quiz_is_passed($user->uid, $quiz->nid, $quiz->vid)) {
    // No access to the page if user hasn't passed the quiz.
    return false;  
  }

  if (user_access('view own quiz certificate') && !quiz_access_results($quiz)) {
    $answered = db_result(db_query_range(
      'SELECT 1
       FROM {quiz_node_results}
       WHERE nid = %d AND uid = %d AND is_evaluated = 1'
    , $quiz->nid, $user->uid, 0, 1));
    if ($answered) {
      return TRUE;
    }
  }
}

/**
 * Callback to certificate page.
 * @param type $quiz
 */
function quiz_certificate_my_certificate($quiz) {
  global $user;
  return quiz_certificate_create_certificate($quiz, $user);
}

function quiz_certificate_my_certificate_pdf($quiz) {
  global $user;
  return quiz_certificate_create_certificate_pdf($quiz, $user);
}

/**
 * Implementation of hook_form_alter().
 * @param type $form
 */
function quiz_certificate_form_alter(&$form, &$form_state, $form_id) {
  if($form_id != 'quiz_results_manage_results_form' || !user_access('view any quiz certificate') || !user_access('view certificates for own quiz')) {
    return;
  }
  
  foreach($form['table']['hover_menu'] as $key => &$item) {
    list($nid, $rid) = explode('-', $key);
    if (quiz_certificate_result_has_passed($nid, $rid)) {
      $item['#value'] = l(t('certificate'), 'node/' . $nid . '/results/' . $rid . '/certificate') . ' | ' . $item['#value'];
    }
  }
}

/**
 * Callback for quiz certificate page.
 */
function quiz_certificate_admin_certificate($quiz, $rid) {
  $uid = db_result(db_query('SELECT uid FROM {quiz_node_results} WHERE result_id = %d', $rid));
  $account = user_load($uid);
  return quiz_certificate_create_certificate($quiz, $account);
}

function quiz_certificate_admin_certificate_pdf($quiz, $rid) {
  $uid = db_result(db_query('SELECT uid FROM {quiz_node_results} WHERE result_id = %d', $rid));
  $account = user_load($uid);
  return quiz_certificate_create_certificate_pdf($quiz, $account);
}

function quiz_certificate_access_certificates($quiz, $rid = NULL) {
  global $user;

  if ($quiz->type !== 'quiz') {
    return FALSE;
  }

  // If rid is set we must make sure the result belongs to the quiz we are
  // viewing results for.
  if (isset($rid)) {
    $sql = 'SELECT qnr.nid
            FROM {quiz_node_results} qnr
            WHERE result_id = %d';
    $res = db_result(db_query($sql, $rid));
    if ($res != $quiz->nid) {
      return FALSE;
    }
  }

  if (!quiz_certificate_result_has_passed($quiz->nid, $rid)) {
    // This quiz result isn't passing, no access.
    return FALSE;
  }
  
  if (user_access('view any quiz certificate')) {
    return TRUE;
  }
  if (user_access('view certificates for own quiz') && $user->uid == $quiz->uid) {
    return TRUE;
  }
}

/**
 * Implemenation of hook_theme().
 */
function quiz_certificate_theme($existing, $type, $theme, $path) {
  return array(
    'quiz_certificate' => array(
      'template' => 'quiz-certificate',
      'arguments' => array('quiz' => NULL, 'account' => NULL),
    ),
    'quiz_certificate_pdf' => array(
      'template' => 'quiz-certificate-pdf',
      'arguments' => array('certificate' => NULL),
    ),
  );
}

function quiz_certificate_preprocess_quiz_certificate(&$vars) {
  $vars['title'] = $vars['quiz']->title;
  $vars['name'] = $vars['account']->name;

  if ($profile = content_profile_load(QUIZ_CERTIFICATE_PROFILE, $vars['account']->uid)) {
    // Profile exists. Replace the username with the profile name
    
    $fname = $profile->{QUIZ_CERTIFICATE_PROFILE_FNAME};
    if($fname) {
      $fname = $fname[0]['value'];
      $name = $fname;
    }
    $lname = $profile->{QUIZ_CERTIFICATE_PROFILE_LNAME};
    if($lname) {
      $lname = $lname[0]['value'];
      $name = $name . ($name ? ' ' : '') . $lname;
    }
    $vars['name'] = $name;
  }

  $vars['download_url'] = filter_xss($_GET['q']) . '/pdf';
  $vars['download_link'] = l(t('download certificate'), $vars['download_url']);
}


/**
 * Helper function to determine if quiz has been passed.
 */
function quiz_certificate_result_has_passed($nid, $rid) {
  $result = db_fetch_array(db_query('SELECT nid, vid, uid FROM {quiz_node_results} WHERE result_id = %d', $rid));
  return quiz_is_passed($result['uid'], $nid, $result['vid']);
}

/**
 * Helper function to create the certificate.
 */
function quiz_certificate_create_certificate($quiz, $account) {
  drupal_add_css(drupal_get_path('module', 'quiz_certificate') . '/quiz_certificate.css');
  $output = theme('quiz_certificate', $quiz, $account);
  return $output;
}

function quiz_certificate_create_certificate_pdf($quiz, $account) {
  $certificate = theme('quiz_certificate', $quiz, $account);
  $output = theme('quiz_certificate_pdf', $certificate);
  $filename = 'certificate-' . strtolower(str_replace(array('/', ' '), '-', check_plain($quiz->title . '-' . $account->name)));
  
  dompdf_stream_pdf($output, $filename);
  
  return;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Hides the correct answer on the results page.
 * This can be moved into a seperate module if hiding the correct answer is
 * needed by not the certificate.
 */
function quiz_certificate_form_quiz_report_form_alter(&$form, &$form_state) {
  foreach($form as &$response) {
    if (isset($response['response']) && isset($response['response']['#value'])) {      
      $response['response']['#value'] = preg_replace('/<img [^>]* alt="Should have chosen" [^>]* \/>/', '', $response['response']['#value']);
    }
  }
}